### ISSUE TITLE
Opening any menu option directly shows an infinite loop

### ISSUE THREAD

**Issue by jonathanvila** [dev-bcn/dev-bcn.github.io#21]
https://www.devbcn.com/codeOfConduct

https://www.devbcn.com/codeOfConduct/?/&/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/~and~/

**Comment by anyulled** [comment]
He probado hoy y está arreglado. ¿Podrías borrar las cookies o probar desde una ventana de incógnito?

**Comment by jonathanvila** [comment]
Cierto. Ahora ya no pasa.
