### ISSUE TITLE
Update Code Of Conduct

### ISSUE THREAD

**Issue by immavalls** [dev-bcn/dev-bcn.github.io#282]
Hi team!

As we discussed related to merging codes of conduct with KCD, https://github.com/cncf/kubernetes-community-days/issues/530, can we update section 5 of the [CoC](https://www.devbcn.com/codeOfConduct) to add an e-mail alias where to report any issues? I can do the PR myself if you can share what e-mail to use.

Thanks!

**Comment by icougil** [comment]
Hi Imma ! 
Sure! Look, we can use the following inbox: privacy@devbcn.com
If you can raise the PR, we will proceed and merge it accordingly  🙂
Thank you very much !!!
